# This is the default configuration file. Enabling and disabling is configured
# in separate files. This file adds all other parameters apart from Enabled.

AllCops:
  Exclude:
    - vendor/**/*
  TargetRubyVersion: 2.5

Layout/CaseIndentation:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Performance/Casecmp:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/ZeroLengthPredicate:
  Enabled: false

LineLength:
  Description: "Limit lines to 100 characters."
  Max: 100
  Enabled: true

Metrics/ClassLength:
  CountComments: false
  Max: 200

AlignHash:
  Description: Align the elements of a hash literal if they span more than one line.
  EnforcedLastArgumentHashStyle: ignore_implicit
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
  Enabled: false

AlignParameters:
  EnforcedStyle: with_first_parameter
  SupportedStyles:
    - with_first_parameter
    - with_fixed_indentation
  Enabled: false

Documentation:
  Description: "Document classes and non-namespace modules."
  Enabled: false

AndOr:
  Description: "Use &&/|| instead of and/or."
  Enabled: false

EndAlignment:
  Description: "Align ends correctly."
  Enabled: true

CollectionMethods:
  Description: "Preferred collection methods."
  Enabled: true
  PreferredMethods:
    collect:  "map"
    collect!: "map!"
    reduce:   "inject"
    detect:   "find"
    find_all: "select"

AssignmentInCondition:
  Description: "Don't use assignment in conditions."
  Enabled: false

DoubleNegation:
  Description: "Checks for uses of double negation (!!)."
  Enabled: false

Style/BlockDelimiters:
  Description: >-
                Avoid using {...} for multi-line blocks (multiline chaining is
                always ugly).
                Prefer {...} over do...end for single-line blocks.
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#single-line-blocks'
  Enabled: false

SpaceBeforeFirstArg:
  Description: "Checks that exactly one space is used between a method name and the first argument for method calls without parentheses."
  Enabled: false

DotPosition:
  Description: "Checks the position of the dot in multi-line method calls."
  Enabled: false

ClassAndModuleChildren:
  Description: "Checks style of children classes and modules."
  Enabled: false

RescueModifier:
  Description: "Avoid using rescue in modifier form"
  Enabled: false

StringLiterals:
  EnforcedStyle: double_quotes

StringLiteralsInInterpolation:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods: ["describe", "context", "let", "it", "before", "included",
                    "define", "factory", "task", "with_versioning",
                    "shared_examples", "shared_examples_for"]

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()
    '%i': '()'
    '%I': '()'
    '%r': '{}'
    '%w': '()'
    '%W': '()'

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Enabled: false
